#今天把Spring boot版本升级到了2.0后，发现原来的文件上传大小限制设置不起作用了，原来的application.properties设置如下：
#
#Spring boot1.0的设置如下：
#1 spring.http.multipart.max-file-size=100mb
#2 spring.http.multipart.max-request-size=1000mb

#Spring boot2.0的设置如下：
#1 #设置上传APP的大小限制
#2 spring.servlet.multipart.max-file-size=100Mb
#3 spring.servlet.multipart.max-request-size=100Mbserver:
server:
#  port: 8888
  tomcat:
    max-swallow-size: 1MB
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  redis:
    host: localhost
    port: 6379